# Generated by Django 4.2.7 on 2023-11-10 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="lokesh",
        ),
    ]
